### ISSUE TITLE
Change email delivery to SMTP

### ISSUE THREAD

**Issue by schillermann** [schillermann/trolleydienst-php#13]
The php mail function is restricted by some providers. Sending via SMTP is more reliable.

**Comment by mikecopestake** [comment]
Hey @schillermann 

I don't know if this is any use, and you may have a better way to accomplish this, but I added [PHPMailer](https://github.com/PHPMailer/PHPMailer) to composer and changed /modules/send_mail_plain.php to the following:

`
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;

//Load Composer's autoloader
require 'vendor/autoload.php';

return function ($to, $subject, $message):bool {

    $mail = new PHPMailer;

    //Server settings
    //$mail->SMTPDebug = SMTP::DEBUG_SERVER;                 //Enable verbose debug output
    $mail->Host       = 'mail.domain.com';                   //Set the SMTP server to send through
    $mail->SMTPAuth   = true;                                //Enable SMTP authentication
    $mail->Username   = 'user@domain.com';                   //SMTP username
    $mail->Password   = 'passsword';                         //SMTP password
    $mail->SMTPSecure = PHPMailer::ENCRYPTION_SMTPS;         //Enable implicit TLS encryption
    $mail->Port       = 465;                                 //TCP port to connect to; use 587 if you have set `SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS`

    //Recipients
    $mail->setFrom('no-reply@domain.com', CONGREGATION_NAME . ' - ' . APPLICATION_NAME);
    $mail->addAddress($to);
    $mail->addReplyTo('reply@domain.com', TEAM_NAME);
    $mail->addBCC('admin@domain.com');
    
    //Content
    $mail->isHTML(true);                                  //Set email format to HTML
    $mail->Subject = $subject;
    $mail->Body    = '<html>' . str_replace("||", "<br>", $message) . '</html>';

    if(!$mail->send()) {
	    return false;
	} else {
	    return true;
	}
};
`

The reason for the str_replace was so that I could add "||" to the email templates to insert line breaks since changing from plain to HTML email. There is probably a better way to do this though.

**Comment by schillermann** [comment]
@mikecopestake great thank you for this good example.
Will be taken over in the software.

**Comment by schillermann** [comment]
Hi @ShahinS2,

hättest du Zeit die Umstellung auf SMTP zu testen?

**Comment by schillermann** [comment]
Hi @mikecopestake,

sorry I saw it too late that PHPMailer uses the GNU Version 2.1 license.
Unfortunately, this is not compatible with the MIT license.

> If you use GPL'ed software in your software (bring together two works) and you then distribute the new work, you have to distribute it under GPL (copyleft).

[Including GPL external library in MIT code](https://stackoverflow.com/questions/11819831/including-gpl-external-library-in-mit-code)

**Comment by schillermann** [comment]
@mikecopestake if you have a suggestion on how best to do this with the license, then bring it on.

**Comment by mikecopestake** [comment]
Ah, I didn't even consider the license, sorry.

Is that still the case even though the trolley script doesn't actually ship with or include PHPMailer as it is installed by the user if they want to use it with composer after downloading the trolley software?

**Comment by schillermann** [comment]
@mikecopestake no problem.
I think this will be too complicated for most, to use composer.

The software is primarily intended for non-commercial use.
Therefore it is also possible to switch to a GNU license, to be able to use more open source libraries.
However, this brings with it some limitations.
You can e.g. not easily use a gpl version 2 with version 3.
The [MIT license](https://en.wikipedia.org/wiki/MIT_License) is the one with the most freedom.

What do you think of [symfony/mailer](https://github.com/symfony/mailer)?
It's under the MIT license.
Is just a suggestion

**Comment by mikecopestake** [comment]
@schillermann

My next question, is what is the purpose of the license? Just to let people know they can do what they want with it? If it was GPL would that be a problem? I can't imagine it will ever be enforced, so it is just a formality really.

I haven't used Symfony before. If it works similarly to PHPMailer then I'm sure it will be a good replacement.

Is SendinBlue being included an issue too? I only used that tool because it is free on most circumstances and very easy to set up.

**Comment by schillermann** [comment]
@mikecopestake each license has its rights and obligations.
It is a contract.
If no license is given, no one may use the software.
Even if it is online on github, at least that's the German law.

With the MIT license, the user has hardly any restrictions.
The GNU license is intended for pure open source projects that are not to be distributed commercially.
If someone else changes the software, they must release the changes and keep the GNU license.
The choice of license must be carefully considered.
If you prefer GPL, which version do you prefer and why?

Do you want to integrate the SendinBlue code into the Trolleydienst software?
If so, what license is the code under?

**Comment by schillermann** [comment]
@mikecopestake when choosing a license, it is important that the license also fits the external packages. Not every license can be used with everyone. Unfortunately, this is part of a public project.

**Comment by mikecopestake** [comment]
@schillermann OK, it is more complex than I realised then. I generally only work with WordPress, which is GPL2.

And I understood your composer choice incorrectly. If you are trying to not use composer for simplicity, then it makes sense for all code to be bundled.

My thinking was that some users will be able to use mail() and it will work fine, on other servers it will not work, so they will have to use another option. I was using PHPMailer previously so included my code for that, but have since switched to Sendinblue so thought I would include that code too so that others can benefit from it.

The sendinblue integration is MIT too, but as I have integrated it using composer, I didn't consider licenses at all anyway, as we aren't including these programs with trolleydienst, they are just there as an optional extra that others can easily install.

With Symfony and Sendinblue being MIT, it makes sense to stay with MIT, and integrate them in the way that you think is best, if my code can be used making it easier for you, great. If it cannot be used and you'd rather take it out entirely, that is absolutely fine. I can continue to use it on my server and I'm happy to share the code with others if they'd like it.

I don't want to impose my ideas on you, I just want to contribute to the project if I can and if it will help you out :-)

**Comment by schillermann** [comment]
@mikecopestake unfortunately, once you make code publicly available, things get more complicated.
If it is imperative to take a license that has more restrictions we are happy to talk about it.
Maybe I overlooked something.
[PHPMailer](https://packagist.org/packages/phpmailer/phpmailer) is good, but I think [symfony/mailer](https://packagist.org/packages/symfony/mailer) will do the same job.
Or is it not possible for you without PHPMailer?

[Sendinblue](https://www.sendinblue.com/) is just an email provider.
Or have I misunderstood?
You will still need a package like PHPMailer or Symfony Mailer for sending emails over SMTP with Sendinblue?

The software is delivered with all external packages under [releases](https://github.com/schillermann/trolleydienst-php/releases).
Therefore the licenses must match each other.

**Comment by mikecopestake** [comment]
Symfony Mailer looks like it will do the same, so it should be a perfect replacement.

SendinBlue is like Mailchimp, their API can be used to send mail through their servers, with no need for an SMTP server so wouldn't need something like PHPMailer.

I was having problems with deliverability, emails were being marked as spam with SMTP, that's the main reason I switched to SendinBlue for transactional emails.

Sorry if I have confused matters!

**Comment by schillermann** [comment]
@mikecopestake I have split the name into first name and last name.
Is last name correct, or rather surname?

**Comment by mikecopestake** [comment]
Fantastic, thank you @schillermann

The JS prompt was because we had publisher's applying to shifts or withdrawing accidentally. Adding the prompt endusres that they intentionally tapped it rather than accidentally whole scrolling.

As for last name or surname, both are technically correct. Last name is used more in the USA and surname is used more British English. I think that technically, if surname is used, first name should instead be "forename".

I would say that going with first and last is probably a little more universally understood.

**Comment by schillermann** [comment]
@mikecopestake and the undo popup window did not help, to avoid an accidental action?
Otherwise I would then take out the undo popup window.
I find 2 queries too many.
What do you think about that?

**Comment by mikecopestake** [comment]
@schillermann I think the problem is that some of the older ones didn't realise they had done it, so didn't tap undo. And instead were accidentally booking themselves in for multiple slots, then looking again later, seeing their name and cancelling.

With the JS alert they see the "are you sure" question and at that point can cancel it.

**Comment by schillermann** [comment]
Thank you @mikecopestake.
This is very valuable information.
Then i will remove the undo popup.

Do you still have time to add the Symfony Mailer to the software?
Or do you know a package, which is better and has the MIT license?

**Comment by mikecopestake** [comment]
Yes I will swap it over and add Symfony Mailer @schillermann. I should have time towards the end of the week.

**Comment by mikecopestake** [comment]
Would you prefer to not use composer and have any scripts added to the software files?

**Comment by schillermann** [comment]
@mikecopestake composer is the default for PHP.
You won't get around it.
Composer does his job well.

The Mailer is in no hurry.

**Comment by mikecopestake** [comment]
On my staging site I tested all emails and all work, except for shift deleted. I tested that on the live v1.6.2 site and it doesn't work there either.

Can anyone else confirm if the delete shift email is working?

**Comment by mikecopestake** [comment]
@schillermann several in our congregation use the report function, we haven't promoted it at all though, so if we do there would probably be greater uptake.

The figures probably wouldn't be used for anything other than monitoring which days/times seem to be the most fruitful.

It would be useful to add 'videos shown' to the report function.

**Comment by schillermann** [comment]
Hi @mikecopestake nice to hear that the report function is being used.
Sure, will add __videos shown__ to the report.

**Comment by schillermann** [comment]
@mikecopestake I looked at your changes.
I'm missing the 2 packages you installed.
How do you install packages with composer?
Do you use `composer require package/xyz`?

**Comment by mikecopestake** [comment]
@schillermann I did use composer require, I believe with the following:

```
composer require sendinblue/api-v3-sdk:8.3.0
composer require symfony/mailer:6.0
```

If you use `composer update` or `composer install` does that not work?

**Comment by schillermann** [comment]
@mikecopestake I think I can't install the packages because the composer.lock isn't in git.
Normally you install packages with `composer install`, but it did not work.

**Comment by mikecopestake** [comment]
@schillermann could it be the PHP version? I think the included version of symfony Mailer needs PHP8 or higher. What version do you have?

**Comment by user-kh** [comment]
Hi @schillermann,
I have read that Composer requires PHP > 8.
In the pruning (readme) it still says PHP 7.
You could add that PHP 8 is only needed if you use symfony/mailer.

**Comment by schillermann** [comment]
Hi @user-kh the software should basically run with PHP 7, no matter which extentions you use.
@mikecopestake had installed a newer symfony/mailer version that required PHP 8.
I set symfony/mailer to an older version that runs with PHP 7.
In the composer.lock file it is mentioned that the software runs with both PHP 7 and 8.

Or have I overlooked anything?

**Comment by user-kh** [comment]
@schillermann 
I hope I can explain it correctly
Please check the trolleydienst-php version 1.11.0 vendor -> composer -> platform_check.php
`if (!(PHP_VERSION_ID >= 80100)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 8.1.0". You are running ' . PHP_VERSION . '.';
}`
When I run this version, composer throws an error.

Second part - Readme (suggestion):

🖥️ Systemanforderungen
Minimum PHP7* und Sqlite muss auf dem Server installiert sein.
* Bei Verwendung von symfony/mailer wird PHP 8.1 benötigt.

**Comment by schillermann** [comment]
@user-kh you are right.
The problem has to do with the sendinblue/api-v3-sdk package.
Sendinblue needs the package guzzlehttp/guzzle and this package is danger.
Almost every version has a vulnerability.
No security gaps are known in the last version, until now.
Therefore we cannot use an older version of it.
And guzzle needs symfony/deprecation-contracts with PHP version 8.1.
I also see no solution to get down from PHP 8.1. :open_mouth:

**Comment by user-kh** [comment]
@schillermann 
OK. Thank you for your research.

I have found a workaround:
If you use the simple phpmailer, then you can the PHP version adjust in: 
vendor -> composer -> platform_check.php
for example to 74000

**Comment by schillermann** [comment]
@user-kh we cannot use phpmailer, because it is not valid with [our license](https://github.com/schillermann/trolleydienst-php/blob/master/LICENSE).
symfony/mailer however, is not the problem.
sendinblue/api-v3-sdk is the package which requires PHP 8.1.

**Comment by schillermann** [comment]
@user-kh I found a work a round to get packages with php 8.1 to 7.4.
You can download the new [version 1.11.1](https://github.com/schillermann/trolleydienst-php/releases/tag/1.11.1).

**Comment by user-kh** [comment]
@schillermann 
Vielen Dank für deine Arbeit.
